export const questions = [
  "Saya sering mencari peluang baru bahkan ketika saya sudah berada di posisi yang nyaman.",
  "Saya lebih suka mengambil risiko yang telah diperhitungkan daripada mengikuti jalan yang aman.",
  "Saya berani memulai sesuatu yang baru meskipun ada kemungkinan gagal.",
  "Saya sering menemukan cara baru untuk menyelesaikan masalah.",
  "Saya menikmati berpikir di luar kebiasaan dan mencoba hal-hal baru.",
  "Saya melihat peluang di mana orang lain melihat masalah.",
  "Saya tetap berusaha meskipun menghadapi kegagalan atau rintangan besar.",
  "Saya tidak mudah menyerah saat proyek atau usaha mengalami kesulitan.",
  "Saya termotivasi oleh tantangan dan bersemangat untuk terus berkembang.",
  "Saya mudah beradaptasi ketika situasi atau rencana berubah.",
  "Saya tidak takut untuk mengubah strategi jika yang sekarang tidak berhasil.",
  "Saya nyaman dengan ketidakpastian dan dapat bekerja di lingkungan yang tidak stabil.",
  "Saya percaya diri dalam mengambil keputusan penting.",
  "Saya mampu mengelola sumber daya (waktu, uang, tenaga) dengan efektif.",
  "Saya menikmati bekerja dalam tim dan mampu memotivasi orang lain untuk mencapai tujuan bersama.",
  "Saya secara aktif membangun hubungan dengan orang-orang yang dapat membantu perkembangan bisnis atau ide saya.",
  "Saya senang bekerja sama dengan orang lain untuk mencapai tujuan bersama.",
  "Saya terbuka untuk belajar dari orang lain dan mengambil manfaat dari pengalaman mereka.",
  "Saya memiliki visi yang jelas tentang tujuan yang ingin saya capai di masa depan.",
  "Saya secara aktif merencanakan langkah-langkah untuk mencapai visi tersebut.",
  "Saya berpikir tentang bagaimana menciptakan dampak jangka panjang melalui usaha saya.",
];
